[package]
name = "thundershare-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.1"
dotenv = "0.15.0"
env_logger = "0.11.1"
jwt = "0.16.0"
sqlx = "0.7.3"
tokio = "1.35.1"
