version: "3"
services:
  backend:
    image: thundershare/thundershare-backend:v0.1.0
    command: /var/app/thundershare-backend
    stdin_open: true
    tty: true
    working_dir: /var/app
    restart: always
    ports: 
      - 8080:8080
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_POST: 8080
      DB_HOST: db
      DB_NAME: thundershare
      DB_USER: pgsql
      DB_PASS: password
      PGDATA: /tmp
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_USER: pgsql
      POSTGRES_PASSWORD: password
      POSTGRES_DB: thundershare
      PGDATA: /tmp
